project1: p1.o PrintSymbolTable.o InsertSymbol.o IsInSymbolTable.o DeleteList.o IsDirective.o IsInstruction.o IsValidSymbol.o 
	gcc  -o project1 p1.o PrintSymbolTable.o InsertSymbol.o IsInSymbolTable.o DeleteList.o IsDirective.o IsInstruction.o IsValidSymbol.o

p1.o: p1.c headers.h
	gcc -c -g -Wall p1.c

PrintSymbolTable.o: PrintSymbolTable.c headers.h
	gcc -c -g -Wall PrintSymbolTable.c

InsertSymbol.o: InsertSymbol.c headers.h
	gcc -c -g -Wall InsertSymbol.c

IsInSymbolTable.o: IsInSymbolTable.c headers.h
	gcc -c -g -Wall IsInSymbolTable.c

DeleteList.o: DeleteList.c headers.h
	gcc -c -g -Wall DeleteList.c

IsDirective.o: IsDirective.c headers.h
	gcc -c -g -Wall IsDirective.c

IsInstruction.o: IsInstruction.c headers.h
	gcc -c -g -Wall IsInstruction.c

IsValidSymbol.o: IsValidSymbol.c headers.h
	gcc -c -g -Wall IsValidSymbol.c
